
function retrieve_current_configuration
{
db2 -x "export to current_audit_tables.txt of del modified by nochardel coldel# 
select
    upper(replace(ap.auditpolicyname, ' ', '_')),
    rtrim(objectschema),
    rtrim(objectname),
    auditstatus,
    contextstatus,
    validatestatus,
    checkingstatus,
    secmaintstatus,
    objmaintstatus,
    sysadminstatus,
    executestatus,
    errortype,
    objecttype,
    subobjecttype
from syscat.auditpolicies ap
left outer join syscat.audituse au on au.auditpolicyid = ap.auditpolicyid
order by ap.auditpolicyname, objectschema, objectname, objecttype, subobjecttype"
}

function get_audit_object()
{
    local policy_line=$1

    objectschema=`echo ${policy_line} | cut -f 2 -d '#'`
    objectname=`echo ${policy_line} | cut -f 3 -d '#'`
    objecttype=`echo ${policy_line} | cut -f 13 -d '#'`
    subobjecttype=`echo ${policy_line} | cut -f 14 -d '#'`

    local audit_object=""
    case ${objecttype} in
        "T" )
            audit_object="table ${objectschema}.${objectname}"
            ;;
        "i" )
            case ${subobjecttype} in
                "G" )
                    audit_object="group ${objectname}"
                    ;;
                "R" )
                    audit_object="role ${objectname}"
                    ;;
                "U" )
                    audit_object="user  ${objectname}"
                    ;;
                * )
                    echo Dit objectsubtype wordt niet ondersteund
                    exit 20
                    ;;
            esac
            ;;
        "g" )
             audit_object="${objectname}"
             ;;
        " " )
            audit_object="database"
            ;;
        * )
            echo De policy category ${objecttype} is nog niet geimplementeerd
            exit 10
            ;;
    esac

    echo "${audit_object}"
}


# Get database configuration from db3auddb
# Connect to db3auddb
db2 connect to db3auddb user db2aixbh using Chymitsj0er1


db2 -x "export to desired_table_configuration of del modified by nochardel coldel# 
select 
    upper(replace(p.auditpolicyname, ' ', '_')),
    rtrim(objectschema),
    case rtrim(objectname) when 'DATABASE' THEN 'CURRENT SERVER' ELSE rtrim(objectname) END,
    auditstatus,
    contextstatus,
    validatestatus,
    checkingstatus,
    secmaintstatus,
    objmaintstatus,
    sysadminstatus,
    executestatus,
    errortype,
    objecttype,
    coalesce(subobjecttype, ' ')
from audit.audit_object obj
join audit.audit_policy p on obj.auditpolicyname = p.auditpolicyname
where databasename = 'IG7ADPDB'
order by p.auditpolicyname, objectschema, objectname, objecttype, subobjecttype"

db2 -x "
select
'create audit policy \"' || upper(replace(p.auditpolicyname, ' ', '_')) || '\" categories ' ||CHR(10)||
   '  audit status ' || audit.translate_status(auditstatus) ||CHR(10) ||
   ', context status ' || audit.translate_status(contextstatus) ||CHR(10) ||
   ', validate status ' || audit.translate_status(validatestatus) ||CHR(10) ||
   ', checking status ' || audit.translate_status(checkingstatus) ||CHR(10) ||
   ', secmaint status ' || audit.translate_status(secmaintstatus) ||CHR(10) ||
   ', objmaint status ' || audit.translate_status(objmaintstatus) ||CHR(10) ||
   ', sysadmin status ' || audit.translate_status(sysadminstatus) ||CHR(10) ||
   ', execute status ' || audit.translate_status(executestatus) ||CHR(10) ||
   ' error type ' || decode(errortype, 'N', 'NORMAL', 'A', 'AUDIT') || ';' ||CHR(10) ||
   ' comment on audit policy \"' || replace(p.auditpolicyname, ' ', '_') || '\" is ''automatically generated by audit framework'';'
from audit.audit_object obj
join audit.audit_policy p on obj.auditpolicyname = p.auditpolicyname
where databasename = 'IG7ADPDB'" > create_desired_table_configuration.sql

db2 disconnect current

# Get current configuration
db2 connect to ig7adpdb

retrieve_current_configuration
# bepaal de checksum voor beide bestanden
csum_desired=`csum desired_table_configuration | cut -f 1 -d ' '`
csum_current=`csum current_audit_tables.txt | cut -f 1 -d ' '`

if [ "${csum_desired}" == "${csum_current}" ]
then
    echo configuratie komt overeen op basis van md5sum
    exit 0
fi

while read policy  
do 
    echo controleer de database voor policy ${policy}
    policy_name=`echo ${policy} | cut -f 1 -d '#'`
    echo Policy_name: ${policy_name}

    if grep "${policy}" current_audit_tables.txt > /dev/null; 
    then
       echo Configuratie komt volledig overeen. Door naar de volgende rij
       continue;
    fi

    grep "${policy_name}#" current_audit_tables.txt > /dev/null
    greprc=$?

    if [ ${greprc} -eq 1 ]
    then
        echo de configuratie voor policy ${policy_name} is niet aanwezig op deze database
        echo Maak de policy ${policy_name} aan op deze database
        sed -n "/create audit policy \"${policy_name}\" /,/comment on audit policy \"${policy_name}\"/p" create_desired_table_configuration.sql > create_policy_${policy_name}.sql
        db2 -svtf create_policy_${policy_name}.sql > create_policy_${policy_name}.log
        db2 commit
        
        # Een policy kan aan meerdere objecten zijn gekoppeld. Voeg daarom de nieuwe policy toe aan current_config 
        retrieve_current_configuration
    else
        echo De policy ${policy_name} is al aanwezig op deze database
    fi

    # We weten nu dat de policy aanwezig is. Indien dit niet het geval was, hebben we deze in de vorige stap aangemaakt.
    # Controleer of de huidige instellingen overeen komen met de gewenste instellingen
    c1=`egrep ^${policy_name}# desired_table_configuration | head -n 1 | cut -f 4-12 -d '#'`
    c2=`egrep ^${policy_name}# current_audit_tables.txt    | head -n 1 | cut -f 4-12 -d '#'`
    
    if [ "$c1" != "$c2" ]
    then
        echo De policy ${policy_name} komt niet overeen met de policy op deze database. Pas de policy aan. 
        # Het wijzigen van de policy is gelijk aan het aanmaken van de policy. Vervang "create" door "alter". 
        # We selecteren alleen de policy die we nu nodig hebben. Dat loopt van "create audit policy" tot en met "comment on audit policy"
        sed -n "/create audit policy \"${policy_name}\" /,/comment on audit policy \"${policy_name}\"/p" create_desired_table_configuration.sql | sed 's/create/alter/' > alter_policy_${policy_name}.sql
        # Wijzig de policy
        db2 -svtf alter_policy_${policy_name}.sql > alter_policy_${policy_name}.log
        db2 commit
 
        # Werk de configuratie bij. Andere object kunnen dezelfde policy gebruiken en we willen deze maar 1 keer wijzigen. 
        retrieve_current_configuration
    else 
        echo De policy komt inhoudelijk overeen met de policy op deze database
    fi
     
    # Mogelijk heeft het aanpassen of toevoegen van de policy het probleem opgelost.
    if grep "${policy}" current_audit_tables.txt > /dev/null; 
    then
       echo De policy ${policy_name} is al juist gekoppeld aan dit object. 
       continue;
    fi

    audit_object="$(get_audit_object "$policy")"

    if [ -z "${audit_object}" ]
    then
        echo Het audit object is niet gevuld
        exit 11
    else     
        echo Koppel policy ${policy_name} aan object ${audit_object}
        db2 audit ${audit_object} using policy \"${policy_name}\"
        db2 commit
    fi
done < desired_table_configuration

# Bepaal opieuw de checksum voor de current_config. Indien gelijk zijn we klaar

retrieve_current_configuration
# bepaal de checksum voor beide bestanden
csum_desired=`csum desired_table_configuration | cut -f 1 -d ' '`
csum_current=`csum current_audit_tables.txt | cut -f 1 -d ' '`

if [ "${csum_desired}" == "${csum_current}" ]
then
    echo configuratie komt overeen op basis van md5sum
    exit 0
fi

while read policy
do
    if grep "$policy" desired_table_configuration > /dev/null
    then
       continue;
    fi

    echo geen match op $policy

    object="$(get_audit_object "$policy")"


    if [ -z "${object}" ]
    then
        echo Het audit object is niet gevuld
        exit 21
    else
        echo ontkoppel policy ${policy_name} van object ${audit_object}
        db2 audit ${object} remove policy
        db2 commit
    fi

done < current_audit_tables.txt


