CATALOG TCPIP NODE N_MON REMOTE devkeydb2l01.keylanehosting.local SERVER 60006;

CATALOG DB QIS AS MON AT NODE N_MON;

create wrapper drda;

CREATE SERVER SERV_MON TYPE DB2/UDB VERSION '11.1' WRAPPER drda AUTHORIZATION "monuser" PASSWORD "monuser" OPTIONS (ADD DBNAME 'MON');

CREATE USER MAPPING FOR monuser SERVER SERV_MON OPTIONS (ADD REMOTE_AUTHID 'monuser', ADD REMOTE_PASSWORD 'monuser');